name: Go

on:
    push:
        branches: [main]
    pull_request:
        branches: ["*"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: ["1.23.x"]
                include:
                    - go: 1.23.x

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
                  cache-dependency-path: "**/go.sum"

            - name: Download Dependencies
              run: |
                  go mod download

            - name: Test
              run: make test
